### ISSUE TITLE
怎么取消主键自增长

### ISSUE THREAD

**Issue by creekmoon** [leecho/mybatis-generator-plus#18]
我是小白，不太会用。我生成出来的东西都不能手动插入主键。请问大佬……该怎么做呢？
![图片](https://user-images.githubusercontent.com/34275580/77845130-e365cf00-71de-11ea-9d48-e38609d06369.png)
生成页面时，“Primary Key”这个地方的值无法删除。
![图片](https://user-images.githubusercontent.com/34275580/77845139-f6789f00-71de-11ea-8723-a68e090cb508.png)
谢谢。

**Comment by leecho** [comment]
不要设置数据库主键
