### ISSUE TITLE
请求添加Resource注解选项

### ISSUE THREAD

**Issue by pdkst** [leecho/mybatis-generator-plus#3]
我司项目用的mybatis的Dao层注解用的不是repository，添加了
```
    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="annotationClass" value="javax.annotation.Resource"/>
    </bean>
```
这个配置导致Dao层使用的只能是javax的`@Resource`注解，不能使用spring的`@Repository`注解，请求添加一个选项来修改`@Resource`选项
![image](https://user-images.githubusercontent.com/8915631/52548559-62e0e500-2e09-11e9-84b2-d9d8963f55ee.png)

**Comment by chuntungho** [comment]
试试Mybatis Builder, 支持自定义，批量生成等

**Comment by pdkst** [comment]
> 试试Mybatis Builder, 支持自定义，批量生成等

我试了一下，很不幸，```Mybatis Builder```带了```mybatis-generator```的一些遗留问题，比如xml标签重复生成等

**Comment by chuntungho** [comment]
最新版本v1.0.3，处于审核中，可通过github下载

**Comment by pdkst** [comment]
> 最新版本v1.0.3，支持xml/java合并，处于审核中，可通过github下载

1.0.3重复的代码从三份变成两份了！加油
